"$schema" = 'https://starship.rs/config-schema.json'
format = """$all$cmd_duration
$character"""

add_newline = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

# [cmd_duration]
# min_time = 10
# show_milliseconds = true
# format = "[$duration](bright-black)"

[directory]
truncation_length = 4
truncation_symbol = '…/'
truncate_to_repo = false

[fill]
symbol = ' '

[golang]
symbol = " "

[nodejs]
symbol = "󰎙 "

[git_metrics]
disabled = false
format = '(([ $added ]($added_style))([ $deleted ]($deleted_style)))'
only_nonzero_diffs = true
added_style = 'green'
deleted_style = 'red'

[git_branch]
symbol = ' '

[line_break]
disabled = true

[jobs]
disabled = true

[battery]
disabled = true
